// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package wirebox

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/orzkratos/demokratos/demo2kratos/internal/biz"
	"github.com/orzkratos/demokratos/demo2kratos/internal/conf"
	"github.com/orzkratos/demokratos/demo2kratos/internal/data"
	"github.com/orzkratos/demokratos/demo2kratos/internal/service"
)

// Injectors from wire.go:

// wireBox 简化的依赖注入容器
func wireBox(server *conf.Server, confData *conf.Data, logger log.Logger) (*WireBox, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	wireboxWireBox := newWireBox(greeterUsecase, greeterService)
	return wireboxWireBox, func() {
		cleanup()
	}, nil
}
